Repository openshift/assisted-installer, pull requests merged in 2021-09, with the labels that each got.

#350 MGMT-7713 Worker won't get updated to 'Waiting for ignition' when installing with IPv6
  src/common/common.go
  src/common/common_test.go
  test_files/mcs_logs.txt
Labels: lgtm, approved, size/XS

#351 MGMT-7750: get efi file according to cpu architecture
  src/ops/ops.go
Labels: lgtm, approved, size/S

#354 NO-ISSUE: Use -v for efibootmgr to get detailed output
  src/ops/ops.go
Labels: lgtm, approved, size/XS

#357 NO-ISSUE: upload controller logs with operator status before must-gather
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: lgtm, approved, size/XS

#359 MGMT-7315: Support IP-based matching of nodes during installation
  src/assisted_installer_controller/assisted_installer_controller.go
  src/common/common.go
  src/common/common_test.go
  src/installer/installer.go
Labels: lgtm, size/L, approved

#358 MGMT-7504: move assisted-installer/controller to use V2 APIs for comm…
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/inventory_client/inventory_client.go
  src/inventory_client/mock_inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
Labels: lgtm, size/L, approved

#360 MGMT-7760: Switch to stream8
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/XS

#356 NO-ISSUE: Add lranjbar to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS
