Repository openshift/assisted-installer, pull requests merged in 2021-11, with the labels that each got.

#373 MGMT-7912: Controller: Add cache to the operators status API
  go.mod
  go.sum
  src/inventory_client/inventory_client.go
Labels: size/M, lgtm, approved

#371 MGMT-8064: Introduce dry run mode to the installer
  src/assisted_installer_controller/assisted_installer_controller.go
  src/config/config.go
  src/config/dry_run_config.go
  src/config/flag_array.go
  src/installer/installer.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/drymock/dry_mode_k8s_mock.go
  src/main/main.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/utils/utils.go
Labels: size/XL, lgtm, approved

#375 MGMT-7912: getmonitors operator cache should not return value on any
  src/inventory_client/inventory_client.go
Labels: lgtm, approved, size/S

#377 Latest triage issues fixes
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: size/M, lgtm, approved

#378 NO-ISSUE - add eliorerz and celebdor to owners
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#379 MGMT-8064: Dry mode multi-node cluster support
  src/config/dry_run_config.go
  src/k8s_client/k8s_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/drymock/dry_mode_k8s_mock.go
  src/main/main.go
  src/ops/ops.go
Labels: lgtm, size/L, approved

#380 MGMT-8293: Adapt assisted installer to latest swagger changes
  go.mod
  go.sum
  src/inventory_client/inventory_client.go
Labels: lgtm, size/L, approved

#381 MGMT-8330: Minimize number of inventory client retries in assisted-co…
  src/inventory_client/inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, approved, size/S
