Repository openshift/assisted-installer, pull requests merged in 2021-07, with the labels that each got.

#319 OCPBUGSM-30066: Retry wait for operator in case it failed
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/utils/utils.go
Labels: approved, lgtm

#298 MGMT-6663: Update progress of operators only when there's a new progress
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: approved, lgtm

#322 NO-ISSUE: Adding sagidayan as a code reviewer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#323 Bug 1979009: Change log message about EFI support
  src/ops/ops.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, size/XS

#324 MGMT-7201: Wrap PostInstallConfigs logs and pass the entire failure message to the service
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: approved, lgtm, size/M

#326 Bug 1979009: Change log message about EFI support
  src/ops/ops.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, size/XS

#325 MGMT-7210 Upgrade Go version to 1.16
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-build
  Dockerfile.assisted-installer-controller
  go.mod
Labels: approved, lgtm, size/XS

#330 NO-ISSUE: Log message before uploading logs to service
  src/installer/installer.go
Labels: approved, lgtm, size/XS

#331 MGMT-7149: Merge wait for operators
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
Labels: approved, lgtm, size/XL

#332 OCPBUGSM-31942: Return error on failed status operator update
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: approved, lgtm, size/XS

#329 MGMT-4893: Add Must-Gather reports when olm controllers fail
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: approved, lgtm, size/L

#327 Bug 1981465: Assisted installer wait for ready master nodes on bootst…
  src/installer/installer.go
  src/installer/installer_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/M

#334 OCPBUGSM-27526: Cluster deployment freeze on Finalizing stage forever on Cluster Version Operator
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: approved, lgtm, size/M

#335 MGMT-4893: quote must-gather-image env variable in controller manifest
  deploy/assisted-installer-controller/assisted-installer-controller-cm.yaml.template
Labels: approved, lgtm, size/XS
