Repository openshift/assisted-installer, pull requests merged in 2021-08, with the labels that each got.

#337 MGMT-3817: assisted-controller should always send logs
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/common/common.go
Labels: approved, lgtm, size/XS

#338 MGMT-7452: Remove token from assisted-installer-controller log
  src/assisted_installer_controller/assisted_installer_controller.go
  src/ops/ops.go
Labels: approved, lgtm, size/XS

#339 OCPBUGSM-32117: Adding ipv6 support to dns busy address workaround
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: approved, lgtm, size/M

#336 MGMT-7417: Change installer and installer controller to support infra…
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/common/common.go
  src/common/common_test.go
  src/config/config.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/inventory_client/inventory_client.go
  src/inventory_client/inventory_client_test.go
  src/inventory_client/mock_inventory_client.go
  src/ops/coreos_installer_log_writer.go
  src/ops/coreos_installer_log_writer_test.go
  src/ops/ops.go
Labels: lgtm, size/L, approved

#340 MGMT-7450: Removing pull secret token from failure logs
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, approved, size/S

#341 Remove installation timeout
  src/config/config.go
Labels: lgtm, approved, size/XS

#342 OCPBUGSM-31802: hosts that were moved to ready state in k8s, didn't send
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: lgtm, approved, size/S

#343 MGMT-7178: Assisted-installer should not reboot worker till min number of masters have joined
  src/installer/installer.go
  src/installer/installer_test.go
Labels: size/M, lgtm, approved

#345 MGMT-7597: Remove ronniel1, razregev, and asalkeld from OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#333 MGMT-7292: Wait for the OLM to be initilized before CR apply
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/utils/utils.go
Labels: lgtm, size/L, approved
