Repository openshift/assisted-installer, pull requests merged in 2021-10, with the labels that each got.

#291 Bug 1966621: Do not use run-level label for assisted-installer namespace
  deploy/assisted-installer-controller/assisted-installer-controller-nm.yaml
  deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: size/M, lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#362 MGMT-4078: Validate console operator in parallel to CVO
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: lgtm, size/L, approved

#367 NO-ISSUE: Add omertuc to code-approvers
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#368 Bug 2010183: LogURL field of the AgentClusterInstall is not filled up…
  src/ops/ops.go
Labels: bugzilla/severity-urgent, lgtm, bugzilla/valid-bug, approved, size/XS

#372 NO-ISSUE: add backofflimit 100 and imagePullPolicy: IfNotPresent to assisted controller
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
Labels: lgtm, approved, size/XS
