Repository openshift/assisted-installer, pull requests merged in 2021-06, with the labels that each got.

#271 MGMT-4668: Add support to create manifest in assisted-installer
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: approved, lgtm

#292 NO-ISSUE: Fix lint error
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: approved, lgtm

#293 NO-ISSUE: Improve logging of apply manifest
  src/assisted_installer_controller/assisted_installer_controller.go
  src/inventory_client/inventory_client.go
  src/ops/ops.go
Labels: approved, lgtm

#295 Publish unit-test junit
  Makefile
Labels: approved, lgtm

#296 Set Jenkinsfile with CI variable set to true
  Jenkinsfile
  skipper.yaml
Labels: approved, lgtm

#297 Fix Jenkins collection of junit files
  Jenkinsfile
Labels: approved, lgtm

#302 NO-ISSUE Add mkowalski to OWNERS/code-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#300 MGMT-6749: Automate ocm-2.3 tag for quay.io/ocpmetal
  Jenkinsfile
Labels: approved, lgtm

#304 NO-ISSUE: Fix bug in the date for ocm image
  Jenkinsfile
Labels: approved, lgtm

#294 Add check commit script
  Makefile
  hack/check-commit-message.sh
  hack/check-commits.sh
Labels: approved, lgtm

#306 OCPBUGSM-30942: ACM/ZTP with Wan emulation, SNO cluster installs do not show as installed although they are
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: approved, lgtm

#307 NO-ISSUE: Extend gitignore
  .gitignore
Labels: approved, lgtm

#301 Bug 1951812: Remove label from AI namespace after cluster installation
  deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#312 NO-ISSUE: Update ocm-2.3 branch with limited approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#315 fix OWNERS files to match group members roles
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#313 Bug 1973314: Update the uefi boot entry use shimx64
  src/ops/ops.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#318 NO-ISSUE Fix build error created when PR #311 merged
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: approved, lgtm
