Repository openshift/assisted-installer, pull requests merged in 2022-05, with the labels that each got.

#457 NO-ISSUE: remove dependabot bumps of docker images
  .github/dependabot.yml
Labels: lgtm, approved, size/XS

#461 MGMT-10348: backofflimit in assisted controller is set in a wrong place and does nothing
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
Labels: lgtm, approved, size/XS

#459 NO-ISSUE: Reverting removal of dependabot image bumps
  .github/dependabot.yml
Labels: lgtm, approved, size/XS

#460 Bug 2086273: Cleanup disk which is part of a raid and have lvm on it
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: lgtm, bugzilla/severity-high, bugzilla/valid-bug, size/L, approved

#451 MGMT-9379: Disregard HA mode for worker.
  src/config/config.go
  src/config/config_test.go
  src/installer/installer.go
Labels: lgtm, size/L, approved

#469 MGMT-10003: save-partlabel and save-partindex coreos-installer args are not honored because the partition is formatted previously
  src/config/config.go
  src/installer/installer.go
  src/installer/installer_test.go
Labels: size/M, lgtm, approved

#475 MGMT-9379: Fix arguments to make sure that HighAvailabilityMode is updated correctly to ensure it is unset for workers.
  src/config/config.go
  src/config/config_test.go
  src/config/dry_run_config.go
  src/main/main.go
Labels: lgtm, size/L, approved
