Repository openshift/assisted-installer, pull requests merged in 2022-12, with the labels that each got.

#589 MGMT-12471: Don't crash if operator isn't monitored by service
  src/assisted_installer_controller/operator_handler.go
Labels: lgtm, approved, size/XS

#594 Remove jira ticket prefix requirements
  Makefile
  hack/check-commit-message.sh
  hack/check-commits.sh
Labels: size/M, lgtm, approved

#583 MGMT-12339: Add extra step to force clean disks with LVM volumes
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/ops/ops_test.go
  src/utils/utils.go
  src/utils/utils_test.go
Labels: lgtm, size/L, approved

#600 MGMT-12984: Add more logs to LVM cleanup
  src/ops/ops.go
Labels: lgtm, approved, size/XS

#597 MGMT-12339: Update host install progress on cleanup error
  src/installer/installer.go
  src/installer/installer_test.go
Labels: lgtm, approved, size/XS

#601 MGMT-12908: Labeling nodes as quick as possible and fixing hostname p…
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, size/L, approved
