Repository openshift/assisted-installer, pull requests merged in 2022-08, with the labels that each got.

#517 MGMT-10085: Get real filepath of RAID device
  src/ops/ops.go
Labels: lgtm, approved, size/XS

#520 [release-ocm-2.5] MGMT-11365: fix flaky installation of golangci-lint (#510)
  Dockerfile.assisted-installer-build
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/ops/ops.go
Labels: lgtm, bugzilla/valid-bug, approved, size/XS

#519 Bug 2119308: save-partlabel and save-partindex coreos-installer args …
  src/config/config.go
  src/installer/installer.go
  src/installer/installer_test.go
Labels: size/M, lgtm, bugzilla/valid-bug, approved, bugzilla/severity-unspecified

#527 MGMT-11170: Report the caller in the log.
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, approved, size/XS

#518 MGMT-11695: Remove all LVM volume groups for installer disk
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved

#532 Bug 2122012: assisted-installer isn't sending the host logs in case th…e installation was successful and cacert was added
  src/ops/ops.go
Labels: lgtm, bugzilla/valid-bug, approved, size/S

#531 MGMT-11565: Add handleOLMEarlySetupBug when waiting for CSV
  deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
Labels: lgtm, size/L, approved
