Repository openshift/assisted-installer, pull requests merged in 2022-07, with the labels that each got.

#492 NO-ISSUE: Add @rccrdpccl as approver
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#495 MGMT-11063: assisted-installer isn't sending the host logs in case the installation was successful and cacert was added
  src/ops/execute/execute.go
  src/ops/execute/mock_execute.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved

#497 MGMT-11100: Add router get router status logic in case of sno failure
  deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  src/utils/utils.go
Labels: lgtm, size/L, approved

#499 MGMT-8855: repeated event messages in wait for olm operators due to cache hits
  src/inventory_client/inventory_client.go
Labels: lgtm, approved, size/XS

#501 BZ-2107887: misleading configuring state when installing with assisted-installer
  src/common/common.go
  src/common/common_test.go
  test_files/mcs_logs.txt
Labels: lgtm, approved, size/S

#506 MGMT-11106: Writing controller logs to file in order to be able to send
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/common/common.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: size/M, lgtm, approved

#507 NO-ISSUE: Add `jhernand` to `OWNERS_ALIASES`
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#512 MGMT-11100: changing url for router status check from console to canary
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: lgtm, approved, size/XS
