Repository openshift/assisted-installer, pull requests merged in 2022-03, with the labels that each got.

#422 MGMT-9358: update containers golang version to 1.17
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS

#384 MGMT-8248: Hot fix for ODF
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/inventory_client/inventory_client.go
  src/inventory_client/mock_inventory_client.go
Labels: lgtm, ok-to-test, size/L, approved

#423 MGMT-9358 update assisted-service to master
  Dockerfile.assisted-installer-controller
  go.mod
  go.sum
  src/k8s_client/k8s_client.go
Labels: size/XL, lgtm, approved

#427 MGMT-9709: Modify assisted installer, to use more efficient queries when accessing the assisted service
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/inventory_client/inventory_client.go
  src/inventory_client/mock_inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
Labels: lgtm, size/L, approved
