Repository openshift/assisted-installer, pull requests merged in 2022-01, with the labels that each got.

#383 MGMT-8781: Fix controller updating configuring status with stale data
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: lgtm, approved, size/S

#386 MGMT-8064: Improve performance of installer/controller dry mode in multi-node clusters
  src/assisted_installer_controller/assisted_installer_controller.go
  src/config/dry_run_config.go
  src/inventory_client/inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/drymock/dry_mode_k8s_mock.go
  src/main/main.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: lgtm, size/L, approved

#387 NO-ISSUE: update assisted-service package
  go.mod
  go.sum
Labels: size/M, lgtm, approved

#385 MGMT-8321: try to clean disk even if there is no VG on it
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: lgtm, size/L, approved
