Repository openshift/assisted-installer, pull requests merged in 2022-06, with the labels that each got.

#477 Bug 2055978: host fail to boot from installation disk in case of multiple active "Red Hat Enterprise Linux" boot entries
  src/ops/ops.go
Labels: lgtm, bugzilla/severity-high, bugzilla/valid-bug, approved, size/S

#478 MGMT-10450: Timeout writing to disk reported from bootstrap node when failing to start bootkube
  src/installer/installer.go
  src/installer/installer_test.go
Labels: lgtm, approved, size/S

#474 NO-ISSUE: update bluemonday/runc/ignition packages
  go.mod
  go.sum
Labels: size/M, lgtm, bugzilla/valid-bug, approved

#480 NO-ISSUE: Add paul-maidment to approvers
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#462 MGMT-10330: Do not restart network manager on single node clusters
  src/installer/installer.go
  src/installer/installer_test.go
Labels: lgtm, approved, size/S

#486 NO-ISSUE: fix typo in word 'operators'
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: lgtm, approved, size/XS

#487 NO-ISSUE: In case must-gather upload failed but logs were gathered already we should retry only upload part
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/ops/ops.go
Labels: lgtm, approved, size/S
