Repository openshift/assisted-installer, pull requests merged in 2022-04, with the labels that each got.

#431 NO-ISSUE: bump assisted-service version
  go.mod
  go.sum
Labels: lgtm, size/L, approved

#432 [release-ocm-2.5] NO-ISSUE: bump assisted-service version
  go.mod
  go.sum
Labels: lgtm, bugzilla/valid-bug, approved, size/S

#434 [release-ocm-2.4] MGMT-9897: bump assisted-service version
  go.mod
  go.sum
Labels: lgtm, bugzilla/valid-bug, approved, size/S

#435 MGMT-9898: In assisted installer, add timeout and retry when worker is waiting for 2 ready masters
  src/installer/installer.go
Labels: size/M, lgtm, approved

#437 Bug 2073998: Modify assisted installer, to use more efficient queries when accessing the assisted service
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/inventory_client/inventory_client.go
  src/inventory_client/mock_inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
Labels: lgtm, bugzilla/severity-high, bugzilla/valid-bug, size/L, approved

#438 MGMT-9971: removing timeout from waiting for 2 master.
  src/installer/installer.go
Labels: size/M, lgtm, approved

#439 MGMT-9985: Eliminate use of global variables in assisted-installer
  src/config/config.go
  src/config/dry_run_config.go
  src/installer/installer.go
  src/k8s_client/k8s_client.go
  src/main/drymock/dry_mode_k8s_mock.go
  src/main/main.go
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved

#441 MGMT-10017: Cluster get to Error when OLM operator failed on applying post manifests
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: lgtm, approved, size/S

#445 MGMT-10077: Use logrus.FieldLogger instead of *logrus.Logger
  src/common/common.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/inventory_client/inventory_client.go
  src/k8s_client/k8s_client.go
  src/main/drymock/dry_mode_k8s_mock.go
  src/ops/coreos_installer_log_writer.go
  src/ops/ops.go
  src/utils/utils.go
Labels: size/M, lgtm, approved

#447 NO-ISSUE: Skip preparation of controller files in dry mode
  src/ops/ops.go
Labels: lgtm, approved, size/XS

#448 MGMT-9244: Prevent assisted-agent from rebooting the node when managed by IPA
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/ops.go
Labels: size/M, lgtm, approved
