Repository openshift/assisted-installer, pull requests merged in 2022-11, with the labels that each got.

#568 OCPBUGS-3166: assisted-installer: pod creation fails due to violations of security policies in 4.12
  deploy/assisted-installer-controller/assisted-installer-controller-nm.yaml
Labels: lgtm, approved, size/XS

#571 MGMT-12467: Remove special handling for installing OCP < 4.7
  src/assisted_installer_controller/assisted_installer_controller.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/utils/utils.go
  src/utils/utils_test.go
Labels: lgtm, size/L, approved

#573 NO-ISSUE: Log informative error in case subscription doesn't have CSV
  src/k8s_client/k8s_client.go
Labels: lgtm, approved, size/XS

#580 change all 'go get' commands to 'go install'
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S

#581 OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18.1.
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-build
  Dockerfile.assisted-installer-controller
  go.mod
  src/assisted_installer_controller/operator_handler.go
  src/ignition/mock_ignition.go
  src/inventory_client/mock_inventory_client.go
  src/k8s_client/mock_k8s_client.go
  src/ops/execute/mock_execute.go
  src/ops/mock_ops.go
Labels: lgtm, size/XXL, approved
