Repository openshift/assisted-installer, pull requests merged in 2022-09, with the labels that each got.

#536 MGMT-11348: Changes for upstream multi-arch support
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
  Makefile
Labels: lgtm, approved, size/S

#539 NO-ISSUE: print boot order after setting it
  go.mod
  go.sum
  src/ops/ops.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#540 MGMT-12038: Controller should upload logs from file on summary logs
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/common/common.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: size/M, lgtm, approved

#541 MGMT-12050: Pinning golang.org/x/sys dependency due to golang incompatibility
  Dockerfile.assisted-installer-build
Labels: lgtm, bugzilla/valid-bug, approved, size/XS

#542 MGMT-12057: Remove enablement of router access logs in controller, not needed anymore
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
Labels: size/M, lgtm, approved

#544 NO-ISSUE: add Adrien as a maintainer
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#543 MGMT-12070: Assisted controller should not set status done on host more than once
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: lgtm, approved, size/S

#545 MGMT-12055: Assisted controller should log if one of the nodes changed it's ip after reboot
  src/assisted_installer_controller/assisted_installer_controller.go
  src/common/common.go
Labels: lgtm, approved, size/S

#550 Update approvers and reviewers lists
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#551 MGMT-12115: assisted-installer-controller Job does not apply Addition…
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
Labels: lgtm, approved, size/S

#552 NO-ISSUE: Remove unused function RemoveLV
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: lgtm, approved, size/S

#553 MGMT-12115: Fix wrong formatting in Controller Pod definition
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
Labels: lgtm, approved, size/XS
