Repository openshift/assisted-installer, pull requests merged in 2022-02, with the labels that each got.

#404 NO-ISSUE: Bump baremetal-operator to the same version as assiste-service
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  src/main/drymock/dry_mode_k8s_mock.go
Labels: lgtm, size/L, approved

#407 NO-ISSUE: Update go-openapi/runtime and fix url building
  go.mod
  go.sum
  src/inventory_client/inventory_client.go
Labels: lgtm, approved, size/S

#413 NO-ISSUE: Fix error log printing the wrong error variable
  src/config/dry_run_config.go
Labels: lgtm, approved, size/XS

#414 NO-ISSUE: Jenkins should only build images
  Jenkinsfile
Labels: lgtm, approved, size/XS

#416 NO-ISSUE: Fix jenkins build
  Jenkinsfile
Labels: lgtm, approved, size/XS

#417 NO-ISSUE: remove Jenkins jobs
  Jenkinsfile
  Makefile
Labels: size/M, lgtm, approved
