Repository openshift/assisted-installer, pull requests merged in 2023-07, with the labels that each got.

#681 OCPBUGS-15068 CVE-2022-21235 github.com/Masterminds/vcs command inj
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#682 NO-ISSUE: Update OWNERS to match master branch
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm, approved, jira/valid-reference

#683 MGMT-15235: Compile with CGO_ENABLED=1 for FIPS
  Makefile
Labels: lgtm, approved, size/XS, jira/valid-reference

#685 [release-ocm-2.6] MGMT-15235: Compile with CGO_ENABLED=1 for FIPS
  Makefile
Labels: lgtm, approved, size/XS, jira/valid-reference

#688 MGMT-15344: Assisted-controller should not timeout on waiting cvo by itself
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: lgtm, approved, size/S, jira/valid-reference

#692 MGMT-15343: dependabot group updates
  .github/dependabot.yml
Labels: lgtm, approved, size/S, jira/valid-reference
