Repository openshift/assisted-installer, pull requests merged in 2023-02, with the labels that each got.

#627 OCPBUGS-7149: IPv6 multinode spoke no moving from rebooting/configuring stage
  src/common/common.go
  src/common/common_test.go
  test_files/mcs_logs.txt
Labels: lgtm, bugzilla/valid-bug, approved, size/S, jira/valid-bug, jira/valid-reference

#628 MGMT-13595: Allow moving node from rebooting to joined
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#634 MGMT-13657: Don't wait for console if it is disabled - ACM 2.6
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  src/main/drymock/dry_mode_k8s_mock.go
Labels: lgtm, size/L, approved, jira/valid-reference

#629 MGMT-13605: Remove uninitialized taint from vSphere nodes
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, size/L, approved, jira/valid-reference

#635 MGMT-13664: Don't crash if operator isn't monitored by service - ACM 2.7
  src/assisted_installer_controller/operator_handler.go
Labels: lgtm, approved, size/XS, jira/valid-reference

#622 MGMT-13292: Add the installed version of the OLM operators in the monitor operators response
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/inventory_client/inventory_client.go
  src/inventory_client/mock_inventory_client.go
  vendor/github.com/openshift/assisted-service/client/installer/installer_client.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_get_ignored_validations_parameters.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_get_ignored_validations_responses.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_set_ignored_validations_parameters.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_set_ignored_validations_responses.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/internal/common/common_unitest_db.go
  vendor/github.com/openshift/assisted-service/internal/common/conversions.go
  vendor/github.com/openshift/assisted-service/internal/common/db.go
  vendor/github.com/openshift/assisted-service/internal/common/test_configuration.go
  vendor/github.com/openshift/assisted-service/internal/common/validations.go
  vendor/github.com/openshift/assisted-service/internal/common/version.go
  vendor/github.com/openshift/assisted-service/internal/constants/files.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/drive_type.go
  vendor/github.com/openshift/assisted-service/models/ignored_validations.go
  vendor/github.com/openshift/assisted-service/models/infra_env.go
  vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  vendor/github.com/openshift/assisted-service/models/operator_monitor_report.go
  vendor/github.com/openshift/assisted-service/models/os_image.go
  vendor/github.com/openshift/assisted-service/models/release_image.go
  vendor/github.com/openshift/assisted-service/pkg/auth/rhsso_authz_handler.go
  vendor/github.com/openshift/assisted-service/pkg/ocm/utils.go
  vendor/github.com/openshift/assisted-service/restapi/configure_assisted_install.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/github.com/openshift/assisted-service/restapi/operations/assisted_install_api.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_get_ignored_validations.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_get_ignored_validations_parameters.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_get_ignored_validations_responses.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_get_ignored_validations_urlbuilder.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_set_ignored_validations.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_set_ignored_validations_parameters.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_set_ignored_validations_responses.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_set_ignored_validations_urlbuilder.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#636 Revert "MGMT-13595: Allow moving node from rebooting to joined"
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#623 MGMT-13568: Add pause mcp while setting new role labels
  deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  vendor/github.com/openshift/machine-config-operator/LICENSE
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/doc.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/register.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#642 NO-ISSUE: Replace iotil by os and io in order to fix lint issues
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/common/common.go
  src/common/common_test.go
  src/ignition/ignition.go
  src/installer/installer_test.go
  src/inventory_client/inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
  src/ops/coreos_installer_log_writer_test.go
  src/ops/ops.go
  src/utils/tarutil_test.go
  src/utils/utils_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#638 MGMT-13710: assisted-installer-controller hangs for 2 minutes before uploading the ingress CA
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/inventory_client/inventory_client.go
  src/utils/utils.go
Labels: size/M, lgtm, approved, jira/valid-reference

#626 MULTIARCH-3387: Set boot device to target disk for powervm
  src/ops/ops.go
  src/ops/ops_test.go
Labels: size/M, lgtm, approved, jira/valid-reference
