Repository openshift/assisted-installer, pull requests merged in 2023-12, with the labels that each got.

#758 MGMT-16370: fix golangci-lint failing to be pulled
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS, jira/valid-reference

#757 MGMT-16266: Indication event showing how often host has been rebooted missing on some nodes
  src/assisted_installer_controller/reboots_notifier.go
  src/assisted_installer_controller/reboots_notifier_test.go
  src/utils/utils.go
Labels: size/M, lgtm, approved, jira/valid-reference

#763 [release-ocm-2.9] MGMT-16370: fix golangci-lint failing to be pulled
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference

#764 [release-ocm-2.8] MGMT-16370: fix golangci-lint failing to be pulled
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference

#765 [release-ocm-2.7] MGMT-16370: fix golangci-lint failing to be pulled
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference
