Repository openshift/assisted-installer, pull requests merged in 2023-11, with the labels that each got.

#748 MGMT-15926: Operators installation fails due to timeout on failed jobs
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
Labels: lgtm, approved, size/S, jira/valid-reference

#752 MGMT-16258: Partitions naming convetion is different for various disk types
  src/ops/ops.go
  src/ops/ops_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#739 OCPBUGS-20049: Remove uninitialized taint for agent-based installs
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
Labels: lgtm, size/L, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
