Repository openshift/assisted-installer, pull requests merged in 2023-08, with the labels that each got.

#693 Revert "MGMT-15235: Compile with CGO_ENABLED=1 for FIPS"
  Makefile
Labels: lgtm, approved, size/XS, jira/valid-reference

#699 MGMT-15235: Compile with CGO_ENABLED=1 for amd64
  Makefile
Labels: lgtm, approved, size/XS, jira/valid-reference

#700 OCPBUGS-4240: allow controller to complete for agent-based installs
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: size/M, lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#702 OCPBUGS-16482: bump golangci-lint to 1.53.1
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS, jira/valid-bug, jira/valid-reference
