Repository openshift/assisted-installer, pull requests merged in 2023-01, with the labels that each got.

#610 MGMT-13141: assisted-installer-controller shouldn't try to update BMH if the cluster platform is not BareMetal
  src/assisted_installer_controller/assisted_installer_controller.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, approved, size/S

#614 OCPBUGS-5715: CVE-2021-4238 assisted-installer-container: goutils
  go.sum
Labels: lgtm, bugzilla/valid-bug, approved, size/XS, jira/valid-bug

#615 MGMT-13131: shorten SNO installation duration
  src/ops/ops.go
Labels: lgtm, approved, size/XS

#618 MGMT-13385: Installation fail due to race condition in etcd bootstrap strategy
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: size/M, lgtm, approved

#613 MGMT-13229: SNO: Start controller when node is not ready, right after joined
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/ops/ops.go
Labels: size/M, lgtm, approved

#619 MGMT-13463: Assisted-controller can fail to send summary logs and we will not have any logs
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/common/common.go
  src/utils/tarutil.go
  src/utils/tarutil_test.go
Labels: lgtm, approved, size/S, jira/valid-reference

#620 MGMT-13507: Apply node labels only when node is Ready
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
Labels: size/M, lgtm, approved, jira/valid-reference
