Repository openshift/assisted-installer, pull requests merged in 2024-07, with the labels that each got.

#862 NO-ISSUE: Replace base golang image in the build Dockerfile
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference

#865 [release-ocm-2.10] NO-ISSUE: Replace base golang image in the build Dockerfile as it is based on centos7 and it is EOL, which results in yum can't reach its repositories (#862)
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference

#867 [release-ocm-2.8] NO-ISSUE: Replace base golang image in the build Dockerfile as it is based on centos7 and it is EOL, which results in yum can't reach its repositories (#862)
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference

#866 [release-ocm-2.9] NO-ISSUE: Replace base golang image in the build Dockerfile as it is based on centos7 and it is EOL, which results in yum can't reach its repositories (#862)
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/S, jira/valid-reference

#868 NO-ISSUE: Fix OWNERS format
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, jira/valid-reference

#874 [release-ocm-2.10] MGMT-18332: Use centos stream 9 as the base image for test container
  Dockerfile.assisted-installer-build
Labels: size/M, lgtm, approved, jira/valid-reference

#873 [release-ocm-2.9] MGMT-18332: Use centos stream 9 as the base image for test container
  Dockerfile.assisted-installer-build
Labels: size/M, lgtm, approved, jira/valid-reference

#875 [release-ocm-2.11] MGMT-18332: Use centos stream 9 as the base image for test container
  Dockerfile.assisted-installer-build
Labels: size/M, lgtm, approved, jira/valid-reference

#872 [release-ocm-2.8] MGMT-18332: Use centos stream 9 as the base image for test container
  Dockerfile.assisted-installer-build
Labels: size/M, lgtm, approved, jira/valid-reference

#876 MGMT-18332: Use centos stream 9 as the base image for test container
  Dockerfile.assisted-installer-build
Labels: size/M, lgtm, approved, jira/valid-reference

#877 OCPBUGS-36779: Reload host inventory on conflict
  src/installer/installer.go
Labels: lgtm, approved, size/XS, jira/valid-bug, jira/severity-important, jira/valid-reference

#885 NO-ISSUE: fixing ARM images builds
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/S, jira/valid-reference

#886 OCPBUGS-31570: Bump to latest preinstall utils for disk cleanup fixes
  go.mod
  go.sum
  vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/disk_ops.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-bug, jira/valid-reference

#887 [release-ocm-2.11] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: size/M, lgtm, approved, jira/valid-reference

#888 [release-ocm-2.10] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/S, jira/valid-reference

#890 [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: size/M, lgtm, approved, jira/valid-reference

#889 [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: size/M, lgtm, approved, jira/valid-reference
