Repository openshift/assisted-installer, pull requests merged in 2024-04, with the labels that each got.

#807 MGMT-17384: Change waiting for encapsulated machine config from retry to wait-for-predicate
  src/installer/installer.go
Labels: lgtm, approved, size/S, jira/valid-reference

#808 MGMT-17305: Extract disk cleanup from the installer to ops package to allow using it in IBI flow
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/disk_ops.go
Labels: lgtm, size/L, approved, jira/valid-reference

#810 NO-ISSUE: Decouple inventoryClient from ops
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: size/M, lgtm, approved, jira/valid-reference

#816 MGMT-16587: Bump runc to v1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#811 NO-ISSUE: Decouple inventoryClient from ops
  src/coreos_logger/coreos_installer_log_writer.go
  src/coreos_logger/coreos_installer_log_writer_test.go
  src/installer/installer.go
  src/ops/mock_ops.go
  src/ops/ops.go
Labels: lgtm, approved, size/S, jira/valid-reference

#812 [release-ocm-2.9] NO-ISSUE: Add missing accounts for PR approvals
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, jira/valid-reference

#813 NO-ISSUE: add missing accounts for PR approvals
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, jira/valid-reference

#814 NO-ISSUE: add missing accounts for PR approvals
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, jira/valid-reference

#824 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS, jira/valid-reference

#826 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS, jira/valid-reference

#825 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS, jira/valid-reference

#760 CORS-2750: Move to rhel9, decouple from cli image
  .ci-operator.yaml
  Dockerfile.assisted-installer-controller.ocp
  Dockerfile.assisted-installer.ocp
Labels: lgtm, approved, size/S, jira/valid-reference

#822 MGMT-16587: Bump runc to v1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#830 MGMT-17591: Bump runc to v1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#818 MGMT-17518: Bump x/net to 0.24.0 to mitigate CVE-2023-45288
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference
