Repository openshift/assisted-installer, pull requests merged in 2024-02, with the labels that each got.

#781 MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#783 [release-ocm-2.9] MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842 (#781)
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#787 MGMT-16966: Problem creating extra partition on main disk in 4.15+
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved, jira/valid-reference

#788 MGMT-16843: Ensure valid hostname during install
  src/installer/installer.go
  src/installer/installer_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#793 [release-ocm-2.8] MGMT-16843: Ensure valid hostname during install
  src/installer/installer.go
  src/installer/installer_test.go
  vendor/github.com/openshift/assisted-service/pkg/validations/validations.go
  vendor/modules.txt
Labels: lgtm, size/L, approved, jira/valid-reference

#792 [release-ocm-2.9] MGMT-16843: Ensure valid hostname during install
  src/installer/installer.go
  src/installer/installer_test.go
  vendor/github.com/openshift/assisted-service/pkg/validations/validations.go
  vendor/modules.txt
Labels: lgtm, size/L, approved, jira/valid-reference

#796 [release-ocm-2.10] MGMT-16878: Set restricted list of approvers
  OWNERS_ALIASES
Labels: lgtm, approved, size/S, jira/valid-reference
