Repository openshift/assisted-installer, pull requests merged in 2024-10, with the labels that each got.

#910 OCPBUGS-41811: (agent-based installer) let the bootstrap wait for workers before the reboot
  src/installer/installer.go
  src/installer/installer_test.go
Labels: lgtm, size/L, approved, jira/valid-bug, jira/valid-reference

#896 OCPBUGS-38466: Allow controller to continue when assisted-service
  go.mod
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/mock_controller.go
  src/common/common.go
  src/common/common_test.go
  src/installer/installer.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, size/L, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#916 [release-ocm-2.12] MGMT-18932: Reduce the owners list
  OWNERS_ALIASES
Labels: lgtm, approved, size/S, jira/valid-reference

#924 NO-ISSUE: Pin gocov version
  Dockerfile.assisted-installer-build
Labels: lgtm, approved, size/XS, jira/valid-reference

#932 NO-ISSUE: Bump PGX version
  go.mod
  go.sum
  vendor/github.com/jackc/pgx/v4/CHANGELOG.md
  vendor/github.com/jackc/pgx/v4/README.md
  vendor/github.com/jackc/pgx/v4/conn.go
  vendor/github.com/jackc/pgx/v4/copy_from.go
  vendor/github.com/jackc/pgx/v4/internal/sanitize/sanitize.go
  vendor/github.com/jackc/pgx/v4/large_objects.go
  vendor/github.com/jackc/pgx/v4/logger.go
  vendor/github.com/jackc/pgx/v4/rows.go
  vendor/github.com/jackc/pgx/v4/stdlib/sql.go
  vendor/github.com/jackc/pgx/v4/tx.go
  vendor/modules.txt
Labels: lgtm, size/L, approved, jira/valid-reference
