Repository openshift/assisted-installer, pull requests merged in 2024-06, with the labels that each got.

#817 MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/reboots_notifier.go
  src/assisted_installer_controller/reboots_notifier_test.go
  src/config/config.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/ops/ops.go
Labels: size/M, lgtm, approved, jira/valid-reference

#852 MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment
  src/assisted_installer_controller/assisted_installer_controller.go
Labels: lgtm, approved, size/XS, jira/valid-reference

#853 [release-ocm-2.9] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/XS, jira/valid-reference

#855 [release-ocm-2.7] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/XS, jira/valid-reference

#854 [release-ocm-2.8] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/XS, jira/valid-reference

#856 [release-ocm-2.11] MGMT-18187: Reduce the list of approvers for ocm-2.11
  OWNERS_ALIASES
Labels: lgtm, approved, size/S, jira/valid-reference
