Repository openshift/assisted-installer, pull requests merged in 2024-12, with the labels that each got.

#943 MGMT-19371: Add downstream dockerfiles for mce
  Dockerfile.assisted-installer-controller-mce
  Dockerfile.assisted-installer-mce
Labels: lgtm, size/L, approved, jira/valid-reference

#947 OCPBUGS-45116: Add retry to mount efi device
  src/ops/ops.go
Labels: lgtm, approved, size/XS, jira/valid-bug, jira/severity-important, jira/valid-reference

#948 MGMT-19390: Update mce's tekton pipelines to be multi-arch
  .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-push.yaml
  .tekton/assisted-installer-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-main-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#960 MGMT-19453: Add downstream dockerfile
  Dockerfile.assisted-installer-controller-downstream
  Dockerfile.assisted-installer-downstream
Labels: size/M, lgtm, approved, jira/valid-reference

#969 MGMT-19474: Configure multi-arch konflux builds for downstream images for assisted-installer
  .tekton/assisted-installer-downstream-main-pull-request.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
Labels: size/M, lgtm, approved, jira/valid-reference

#970 MGMT-19474: Configure multi-arch konflux builds for downstream images for assisted-installer-controller
  .tekton/assisted-installer-controller-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-downstream-main-push.yaml
Labels: size/M, lgtm, approved, jira/valid-reference

#971 MGMT-19507: Stop using multi-arch builds in konflux
  .tekton/assisted-installer-controller-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-downstream-main-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-push.yaml
  .tekton/assisted-installer-downstream-main-pull-request.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
  .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-main-push.yaml
Labels: size/M, lgtm, approved, jira/valid-reference

#984 [release-ocm-2.11] MGMT-19537: Bump golang.org/x/net to 0.33.0
  Dockerfile.assisted-installer-build
  go.mod
  go.sum
  src/assisted_installer_controller/mock_controller.go
  src/assisted_installer_controller/mock_reboots_notifier.go
  src/ignition/mock_ignition.go
  src/inventory_client/mock_inventory_client.go
  src/k8s_client/mock_k8s_client.go
  src/ops/execute/mock_execute.go
  src/ops/mock_ops.go
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#985 [release-ocm-2.12] MGMT-19537: Bump golang.org/x/net to 0.33.0
  Dockerfile.assisted-installer-build
  go.mod
  go.sum
  src/assisted_installer_controller/mock_controller.go
  src/assisted_installer_controller/mock_reboots_notifier.go
  src/ignition/mock_ignition.go
  src/inventory_client/mock_inventory_client.go
  src/k8s_client/mock_k8s_client.go
  src/ops/execute/mock_execute.go
  src/ops/mock_ops.go
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#981 MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#987 [release-ocm-2.9] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#988 [release-ocm-2.10] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#997 NO-ISSUE: update gin version
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S, jira/valid-reference
