Repository openshift/assisted-installer, pull requests merged in 2024-05, with the labels that each got.

#840 MGMT-17305: Moving disk operations to new repo
  go.mod
  go.sum
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/mock_controller.go
  src/assisted_installer_controller/mock_reboots_notifier.go
  src/assisted_installer_controller/reboots_notifier_test.go
  src/common/common_test.go
  src/coreos_logger/coreos_installer_log_writer_test.go
  src/ignition/mock_ignition.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/inventory_client/mock_inventory_client.go
  src/k8s_client/mock_k8s_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/main/assisted-installer-controller/assisted_installer_main_test.go
  src/main/drymock/dry_mode_k8s_mock.go
  src/ops/disk_ops.go
  src/ops/execute/execute.go
  src/ops/execute/mock_execute.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/ops/ops_test.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/disk_ops.go
  vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/execute_interface.go
  vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/mock_disk_ops.go
  vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/mock_execute_interface.go
  vendor/go.uber.org/mock/AUTHORS
  vendor/go.uber.org/mock/LICENSE
  vendor/go.uber.org/mock/gomock/call.go
  vendor/go.uber.org/mock/gomock/callset.go
  vendor/go.uber.org/mock/gomock/controller.go
  vendor/go.uber.org/mock/gomock/doc.go
  vendor/go.uber.org/mock/gomock/matchers.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved, jira/valid-reference

#823 OCPBUGS-32105: Fix race to mark node Joined
  src/installer/installer.go
  src/inventory_client/inventory_client.go
Labels: lgtm, approved, size/S, jira/valid-bug, jira/valid-reference

#839 MGMT-16843: Use hostnamectl to replace illegal hostname
  src/installer/installer.go
  src/ops/ops.go
Labels: lgtm, approved, size/S, jira/valid-reference
