Repository openshift/assisted-installer, pull requests merged in 2024-03, with the labels that each got.

#794 [release-4.14] MGMT-16843: Ensure valid hostname during install
  Dockerfile.assisted-installer-build
  src/installer/installer.go
  src/installer/installer_test.go
  vendor/github.com/openshift/assisted-service/pkg/validations/validations.go
  vendor/modules.txt
Labels: lgtm, size/L, approved, jira/valid-reference

#798 MGMT-16993: [STG] avoid reboot not working correctly when there is a partition on installation disk
  src/ops/ops.go
Labels: lgtm, approved, size/XS, jira/valid-reference

#800 OCPBUGS-30056: RAN - SNO 4.16 deployment - Failed at Rebooting in agent
  src/ops/ops.go
  src/ops/ops_test.go
Labels: size/M, lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference
