Repository openshift/assisted-installer, pull requests merged in 2025-06, with the labels that each got.

#1079 MGMT-11622: operator status should be logged
  src/assisted_installer_controller/operator_handler.go
Labels: lgtm, approved, size/XS, jira/valid-reference

#1126 NO-ISSUE: Modify Konflux YAMLs to ocm-2.15
  .tekton/assisted-installer-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-15-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-15-push.yaml
Labels: size/M, lgtm, approved, jira/valid-reference

#1129 NO-ISSUE: Add konflux service account migration
  .tekton/assisted-installer-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-15-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-15-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#1128 NO-ISSUE: Konflux service account migration
  .tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#1137 ACM-21380: Make ACM builds multi-arch
  .tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#1136 ACM-21380: Make ACM builds multi-arch
  .tekton/assisted-installer-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-15-push.yaml
  .tekton/assisted-installer-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-15-push.yaml
  .tekton/assisted-installer-controller-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-main-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#1141 MGMT-20858: apply-tag migration
  .tekton/assisted-installer-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-13-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-13-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#1142 MGMT-20858: apply-tag migration
  .tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-controller-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-ds-main-push.yaml
  .tekton/assisted-installer-ds-main-pull-request.yaml
  .tekton/assisted-installer-ds-main-push.yaml
Labels: lgtm, size/XXL, approved, jira/valid-reference
