Repository openshift/assisted-installer, pull requests merged in 2025-09, with the labels that each got.

#1245 NO-ISSUE: Update konflux pipelines to use remote pipeline
  .tekton/assisted-installer-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-13-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-13-push.yaml
Labels: lgtm, size/XXL, approved, jira/valid-reference

#1214 [master] MGMT-20756: assisted installer naive string concatenation for partition finding
  src/ops/ops.go
  src/ops/ops_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#1247 KONFLUX-6210: fix and set name and cpe label for assisted-installer-ds-main
  Dockerfile.assisted-installer-downstream
Labels: lgtm, approved, size/XS, jira/valid-reference
