Repository openshift/assisted-installer, pull requests merged in 2025-01, with the labels that each got.

#1001 MGMT-19595: Push latest tag for downstream images after merge to konflux int repo
  .tekton/assisted-installer-controller-downstream-main-push.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
Labels: lgtm, approved, size/XS, jira/valid-reference

#1002 MGMT-19381: Change downstream base images to rhel9.4 instead of ubi9
  Dockerfile.assisted-installer-controller-downstream
  Dockerfile.assisted-installer-controller-mce
  Dockerfile.assisted-installer-downstream
  Dockerfile.assisted-installer-mce
Labels: lgtm, approved, size/XS, jira/valid-reference

#1004 MGMT-19645: Configure a few things for releasing in konflux
  .tekton/assisted-installer-controller-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-downstream-main-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-push.yaml
  .tekton/assisted-installer-downstream-main-pull-request.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
  .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-main-push.yaml
  Dockerfile.assisted-installer-controller-downstream
  Dockerfile.assisted-installer-controller-mce
  Dockerfile.assisted-installer-downstream
  Dockerfile.assisted-installer-mce
  rpm-prefetching/README.md
  rpm-prefetching/assisted-installer-controller/rpms.in.yaml
  rpm-prefetching/assisted-installer-controller/rpms.lock.yaml
  rpm-prefetching/assisted-installer/rpms.in.yaml
  rpm-prefetching/assisted-installer/rpms.lock.yaml
Labels: lgtm, size/L, approved, jira/valid-reference

#1008 NO-ISSUE: Make konflux builds for downstream images to be multi-arch
  .tekton/assisted-installer-controller-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-downstream-main-push.yaml
  .tekton/assisted-installer-downstream-main-pull-request.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
Labels: lgtm, ok-to-test, approved, size/S, jira/valid-reference

#1009 MGMT-19734: Add renovate config to limit number of PRs
  renovate.json
Labels: lgtm, approved, size/XS, jira/valid-reference

#1010 MGMT-19748: Configure snyk ignore
  .tekton/assisted-installer-controller-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-downstream-main-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-push.yaml
  .tekton/assisted-installer-downstream-main-pull-request.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
  .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-main-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#1013 NO-ISSUE: Update buildah image to fix a bug with SBOM
  .tekton/assisted-installer-controller-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-downstream-main-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-controller-mce-downstream-main-push.yaml
  .tekton/assisted-installer-downstream-main-pull-request.yaml
  .tekton/assisted-installer-downstream-main-push.yaml
  .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-mce-downstream-main-push.yaml
Labels: lgtm, approved, size/S, jira/valid-reference

#1003 MGMT-19100: Install to the current boot device when CoreosImage is set
  src/config/config.go
  src/config/config_test.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1014 MGMT-19621: Fix Race condition between the OLM operators monitor to the cluster installation monitor
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/assisted_installer_controller/operator_handler.go
  src/inventory_client/inventory_client.go
  src/inventory_client/mock_inventory_client.go
  src/main/assisted-installer-controller/assisted_installer_main.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1018 MGMT-19101: Respect installer args
  src/installer/installer.go
  src/installer/installer_test.go
  src/ops/mock_ops.go
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1024 MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-installer
  Dockerfile.assisted-installer-controller
Labels: lgtm, approved, size/S, jira/valid-reference
