Repository openshift/assisted-installer, pull requests merged in 2025-05, with the labels that each got.

#1113 MGMT-20534: Move getting Node replicas into waitForNodes
  go.mod
  src/installer/installer.go
  src/installer/installer_test.go
Labels: size/M, lgtm, approved, jira/valid-reference

#1104 NO-ISSUE: Apply Konflux migration
  .tekton/assisted-installer-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-13-push.yaml
  .tekton/assisted-installer-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-13-push.yaml
  .tekton/assisted-installer-controller-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-ds-main-push.yaml
  .tekton/assisted-installer-ds-main-pull-request.yaml
  .tekton/assisted-installer-ds-main-push.yaml
Labels: lgtm, size/XXL, approved, jira/valid-reference

#1117 MGMT-20567: Enable HTTP endpoint for MCO ignition
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, size/L, approved, jira/valid-reference

#1094 OCPBUGS-53717: Bump jwt to 4.5.2 in release-4.13
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/modules.txt
Labels: cherry-pick-approved, lgtm, size/L, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1123 MGMT-19973: Use rsync over cp to set up networking files for first boot
  src/ops/ops.go
  src/ops/ops_test.go
Labels: lgtm, approved, size/XS, jira/valid-reference
