Repository openshift/assisted-installer, pull requests merged in 2025-02, with the labels that each got.

#1034 MGMT-19950: Modify Konflux YAMLs to ocm-2.14
  .tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
Labels: size/M, lgtm, approved, jira/valid-reference

#1035 [release-ocm-2.13] MGMT-19953: Reduce the OWNERS list for release-ocm-2.13 as it is feature complete
  OWNERS_ALIASES
Labels: lgtm, approved, size/S, jira/valid-reference

#1027 MGMT-19421: phase 1 of replacing the refference HighAvailabilityMode with ControlPlaneCount
  deploy/assisted-installer-controller/assisted-installer-controller-cm.yaml.template
  deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
  src/assisted_installer_controller/assisted_installer_controller.go
  src/assisted_installer_controller/assisted_installer_controller_test.go
  src/config/config.go
  src/config/config_test.go
  src/installer/installer.go
  src/installer/installer_test.go
  src/main/assisted-installer-controller/assisted_installer_main.go
  src/ops/ops.go
Labels: size/M, lgtm, approved, jira/valid-reference

#1037 [release-ocm-2.11] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-installer
Labels: lgtm, approved, size/XS, jira/valid-reference

#1038 [release-ocm-2.10] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-installer
Labels: lgtm, approved, size/XS, jira/valid-reference

#1039 [release-ocm-2.9] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-installer
Labels: lgtm, approved, size/XS, jira/valid-reference

#1040 [release-ocm-2.13] NO-ISSUE: Trigger new MCE 2.8 pipeline
  README.md
Labels: lgtm, approved, size/XS, jira/valid-reference

#1041 Revert "[release-ocm-2.13] NO-ISSUE: Trigger new MCE 2.8 pipeline"
  README.md
Labels: lgtm, approved, size/XS, jira/valid-reference
