Repository openshift/assisted-installer, pull requests merged in 2025-04, with the labels that each got.

#1086 OCPBUGS-53719: Bump jwt to 4.5.2 in release-4.17
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1099 [release-ocm-2.11]-ACM-19179: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#1098 [release-ocm-2.12]-ACM-19175: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#1100 [release-ocm-2.10]-ACM-19171: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#1101 [release-ocm-2.9]-ACM-19177: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#1097 [release-ocm-2.13]-ACM-19178: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, lgtm, approved, jira/valid-reference

#1091 OCPBUGS-53718: Bump jwt to 4.5.2 in release-4.16
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/M, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1105 NO-ISSUE: Apply konflux migration
  .tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-controller-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-acm-ds-main-push.yaml
  .tekton/assisted-installer-controller-ds-main-pull-request.yaml
  .tekton/assisted-installer-controller-ds-main-push.yaml
  .tekton/assisted-installer-ds-main-pull-request.yaml
  .tekton/assisted-installer-ds-main-push.yaml
Labels: size/M, lgtm, approved, jira/valid-reference

#1106 MGMT-20479: Update assisted-installer to allow TNA Clusters
  src/installer/installer.go
  src/installer/installer_test.go
  src/k8s_client/k8s_client.go
  src/k8s_client/mock_k8s_client.go
  src/main/drymock/dry_mode_k8s_mock.go
Labels: lgtm, size/L, approved, jira/valid-reference
